import pandas as pd
s=pd.Series([1,2,3,4,5],index=["a","b","c","d","e"])
print(s)
df=pd.DataFrame({"name":["Rahul","Rohan","Subham"],"mark":[100,80,50]})
print(df)
# print(df.sort())
df=pd.read_csv("Linear Practice/seeds.csv")
print(df)
print(df.info())
print(df.describe())
print(df["Area"])
print(df[["Area","Perimeter"]])
print(df.iloc[0])
print(df.head())
print(df.dropna())